<?php

namespace Core\Init;



use Core\Annotation\Bean;
use Core\Pool\Pool;

/**
 * @Bean()
 */
class RedisPool extends Pool
{
    public function __construct($min = 5, $max = 10, $timeOut = 10)
    {
        global $GLOBALS_CONFIG;
        $poolConfig = $GLOBALS_CONFIG['redisPool']['default'];
        parent::__construct($poolConfig['min'], $poolConfig['max'], $poolConfig['timeOut']);
        $this->initPool();
    }

    public function createConnectionInstance()
    {
        global $GLOBALS_CONFIG;
        $config = $GLOBALS_CONFIG['redis']['default'];

        {
            $host = $config['host'];
            $port = $config['port'];
            $auth = $config['auth'];
            $redis = new \Redis();
            $redis->connect($host, $port);
            if ($auth)
            {
                $redis->auth($auth);
            }
        }

        return $redis;
    }

    public function initPool()
    {
        var_dump('初始化redis');
        parent::initPool(); // TODO: Change the autogenerated stub
    }
}